### ISSUE TITLE
Add support HTTP status code, bytes written and potentially other data (?) to the middleware package

### ISSUE THREAD

**Issue by opalmer** [secureworks/logger#10]
Currently there's no way to log the status code or bytes written to the client using the middleware. Both of these can be useful when trying to debug issues or when just generally looking at logs to pickup on patterns of requests. It would be nice there was a way to extract this data from the response writer so it can be logged after a reply to a client is sent.

**Comment by hews** [comment]
Seems like a bit of an oversight, eh? 😬

**Comment by hews** [comment]
The proposed fix in #12 means breaking the API, so the MR suggests merging to the v2 working branch
