### ISSUE TITLE
middleware: HTTPRequestMiddleware should repanic http.ErrAbortHandler

### ISSUE THREAD

**Issue by iaburton** [secureworks/logger#14]
The current HTTPRequestMiddleware does a good job of capturing panics, checking if they're errors, and logging them. However if that [error](https://github.com/secureworks/logger/blob/2022b2f28a5c668343e1bc05f1fe3165986b6c08/middleware/middleware.go) happens to be [http.ErrAbortHandler](https://pkg.go.dev/net/http#pkg-variables) then in order for that value to function correctly it should be re-panic'd

>If ServeHTTP panics, the server (the caller of ServeHTTP) assumes that the effect of the panic was isolated to the active request. It recovers the panic, logs a stack trace to the server error log, and either closes the network connection or sends an HTTP/2 RST_STREAM, depending on the HTTP protocol. **To abort a handler so the client sees an interrupted response but the server doesn't log an error, panic with the value ErrAbortHandler.**

- [net/http](https://pkg.go.dev/net/http#Handler)

We may want to allow configurable errors/conditions to be checked and/or repanic'd for greatest flexibility.

**Comment by hews** [comment]
> We may want to allow configurable errors/conditions to be checked and/or repanic'd for greatest flexibility.

Would this be something we check for and handle specifically in the code or outsource to a configurable handler or stack of handlers?

**Comment by iaburton** [comment]
> > We may want to allow configurable errors/conditions to be checked and/or repanic'd for greatest flexibility.
> 
> Would this be something we check for and handle specifically in the code or outsource to a configurable handler or stack of handlers?

Well, this issue was originally about the former; specific to `http.ErrAbortHandler`. While this pattern isn't a great one (panicing with a special value), it cannot be changed in the std lib due to compatibility guarantees and so I think if someone wrote code expecting this to work and it didn't because our middleware caught it, it would be "unexpected behavior". I was reminded of this yesterday when I saw this exact error (`http.ErrAbortHandler`) in Sentry, which it shouldn't be, cause it should have gone all the way back to the http.Server to handle as is documented in net/http.

To be honest I think most forget this exists in the http package, like I had. In fact IIRC this is how you're supposed to "stop" a malicious request from sending data (by closing/interrupting the connection, beneath http as a protocol). You can hijack the connection but that doesn't work with http2; this special panic is the only way to do it with all http connections afaik. So I'd argue this is something to fix. However "for greatest flexibility" I think maybe we should allow configuration of how panics/recovery are done. Be that a call back for recovered data (like call a callback if recover returned something), or a map to sentinel values, I'm not sure yet.

We can split these into two issues as well, if we just want to fix/handle `http.ErrAbortHandler` first.
