### ISSUE TITLE
Bad docs for testlogger

### ISSUE THREAD

**Issue by hews** [secureworks/logger#5]
Docs for `testlogger` suggest wrong type assertion to get back a `testlogger` type:

https://github.com/secureworks/logger/blob/2022b2f28a5c668343e1bc05f1fe3165986b6c08/testlogger/testlogger.go#L34

Should be:

```go
logger, _ := l.(*testlogger.Logger)
```

**Comment by hews** [comment]
Should testlogger.New return a *testlogger.Logger?

**Comment by hews** [comment]
testlogger should implement UnderlyingLogger.

should have a testlogger.MustNew(...) (logger) function.

**Comment by iaburton** [comment]
> Should testlogger.New return a *testlogger.Logger?

That, and/or another function akin to `NewTestLogger` that returns the concrete type. Having New do it might be fine as well, as long as it's still available from log.Open
