### ISSUE TITLE
Middleware fields, or really any pre-defined field, should be overridable.

### ISSUE THREAD

**Issue by opalmer** [secureworks/logger#9]
I was looking at using the middlware portion of the SDK to log and capture incoming HTTP requests. Unfortunately, it doesn't allow you to override the fields use in the logger. While this isn't a huge deal, it does make the logs harder to work with and search on in a system that already has pre-defined criteria. With DataDog as an example if I provide log messages with these attributes they'll automatically be searchable:

https://docs.datadoghq.com/logs/log_configuration/attributes_naming_convention/#http-requests

In the best case, you have a callable function you can use to overwrite or extend the logging message based on the incoming request. At a minimum though just being able to override the existing fields would be fine.

**Comment by hews** [comment]
This is something I noticed: that DD is using different field names than we are here. I feel like it may make sense to switch to using those as the default:

```
ReqDuration   = "request_duration"
ReqPath       = "http_path"
ReqMethod     = "http_method"
ReqRemoteAddr = "http_remote_addr"
```

However, I can't see an obvious to replace them without making the options and interface for setting up the middleware cludgey and too numerous with a system better than what we currently have:

```go
// This in effect changes what field name we use for request method, eg:
mware := middleware.NewHTTPRequestMiddleware(logger, log.INFO, &middleware.HTTPRequestLogAttributes{
    SkipMethod: true,
    Synthetics: map[string]func(*http.Request) string{
        "X-Alt-Method-Header": func(r *http.Request) string { return r.Method },
    },
})
```

In fact, using the "Skip..." boolean fields, as opposed to like `Skip []string // List of field names.` was meant to make it more obvious and simpler to do such a thing.

**Comment by hews** [comment]
OK, going to come up with a whole new Middleware configuration interface for v2, and will handle this accordingly.
